language: minimal

git:
    depth: false

env:
    global:
        - HUGO_VERSION="0.73.0"

install:
    - curl --retry 100 -sL https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.deb --output $HOME/hugo.deb
    - sudo apt install $HOME/hugo.deb

script:
    - cd slides
    - hugo version
    - hugo

notifications:
    email:
        recipients:
            - danilo.pianini@unibo.it
            - angelo.croatti@unibo.it
        on_success: never
        
