name: Check Gradle projects
on:
  push:
    tags: '*'
    branches-ignore:
      - 'autodelivery**'
      - 'bump-**'
      - 'renovate/**'
    paths-ignore:
      - 'README.md'
      - 'CHANGELOG.md'
      - 'LICENSE'
  pull_request:

jobs:
  Check-Project-0:
    strategy:
      matrix:
        os: [windows, macos, ubuntu]
    runs-on: ${{ matrix.os }}-latest
    env:
      TERM: dumb
    steps:
      - name: Checkout
        uses: danysk/action-checkout@0.1.0
      - uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 16
      - name: Configure the Windows Pagefile
        if: ${{ runner.os == 'Windows' }}
        uses: al-cheb/configure-pagefile-action@v1.2
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-    steps:
      - name: Checkout
        uses: danysk/action-checkout@0.1.0
      - run: cd code/automation
      - run: ./integrity-check.sh
