name: Update Hugo
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  Find-Updates:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Find latest Hugo version
        id: find
        run: |
          LATEST_HUGO=$(curl -H "Accept: application/vnd.github.v3+json" "https://api.github.com/repos/gohugoio/hugo/releases/latest" | jq -r ".name" | cut -c2-)
          echo Found version $HUGO
          echo "::set-output name=hugo-version::$LATEST_HUGO\n"
      - name: Update the build workflow
        run: |
          sed -i .github/workflows/build-and-deploy.yml -e "s/HUGO_VERSION\\: \".*\"/HUGO_VERSION: \"$HUGO_VERSION\"/"
      - name: Open pull request
        uses: peter-evans/create-pull-request@v3
        env:
          PR_TOKEN: ${{ secrets.AUTOMERGE_TOKEN }}
        with:
          token: PR_TOKEN
